#!/usr/bin/python
import signal
import sys
import os
import subprocess

sys.path.append("/usr/local/IBSng/addons/pexpect")
import pexpect

TIMEOUT = 10


def main():
    doRSH(sys.argv[1], sys.argv[2], TIMEOUT)


def doRSH(host, command, timeout):

    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    # Retrieve the output and exit code
    output = result.stdout
    log_file = '/var/log/output.log'

    # Print or use the captured output as needed
    print(output)
    sys.stdout.write(output)
    with open(log_file, 'w') as f:
        f.write(output)




main()
