#!/usr/bin/python
import signal
import sys
import os
import subprocess

sys.path.append("/usr/local/IBSng/addons/pexpect")
import pexpect

TIMEOUT = 10


def main():
    doRSH(sys.argv[1], sys.argv[2], TIMEOUT)


def doRSH(host, command, timeout):
    # Execute the command locally
    exit_code = subprocess.call(command, shell=True)

    # Retrieve the output
    output = subprocess.check_output(command, shell=True)

    # Print or use the captured output as needed
    print(output)
    sys.stdout.write(output)

    log_file = '/var/log/output.log'

    # Write the output to the log file
    with open(log_file, 'w') as f:
        f.write(output)


main()
